# Generated by Django 4.2.3 on 2023-07-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegory', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proverbs.origin')),
            ],
        ),
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('published', models.DateField()),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('origin', models.ManyToManyField(blank=True, through='proverbs.OriginConnection', to='proverbs.origin')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proverbs.tag')),
                ('proverb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proverbs.proverb')),
            ],
        ),
        migrations.AddField(
            model_name='proverb',
            name='tag',
            field=models.ManyToManyField(blank=True, through='proverbs.TagConnection', to='proverbs.tag'),
        ),
        migrations.AddField(
            model_name='originconnection',
            name='proverb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proverbs.proverb'),
        ),
    ]
